#!/usr/bin/env bash

# https://brew.sh/
if ! which brew > /dev/null; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# https://github.com/zdharma/zinit
if [ ! -d $HOME/.zinit/bin ]; then
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma/zinit/master/doc/install.sh)"
fi

# https://github.com/junegunn/vim-plug
vim_plug=$HOME/.vim/autoload/plug.vim
if [ ! -f $vim_plug ]; then
  curl -fLo $vim_plug --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

dotfiles_dir=$HOME/src/github.com/masahir02/dotfiles
if [ ! -d $dotfiles_dir ]; then
  git clone git@github.com:masahir02/dotfiles.git $dotfiles_dir
fi

targets=(
  .gemrc
  .hammerspoon
  .psqlrc
  .tmux.conf
  .zshrc
  .Brewfile
  .vimrc
  bin
)
for target in ${targets[@]}; do ln -sfv $dotfiles_dir/$target $HOME; done

[[ ! -f $HOME/.gitconfig ]] && cp -v $dotfiles_dir/.gitconfig $HOME

brew bundle --global
vim +PlugInstall +qa
