#!/usr/bin/env bash

dotfiles_dir=$HOME/src/github.com/masahir02/dotfiles
if [ ! -d $dotfiles_dir ]; then
  git clone git@github.com:masahir02/dotfiles.git $dotfiles_dir
fi

vim_plug=$HOME/.vim/autoload/plug.vim
if [ ! -f $vim_plug ]; then
  curl -fLo $vim_plug --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

targets=(
  .gemrc
  .hammerspoon
  .psqlrc
  .tmux.conf
  .zshrc
  .Brewfile
  .Brewfile.lock.json
  .vimrc
  bin
)
for target in ${targets[@]}; do ln -sfv $dotfiles_dir/$target $HOME; done

[[ ! -f $HOME/.gitconfig ]] && cp -v $dotfiles_dir/.gitconfig $HOME

brew bundle --global
vim +PlugInstall +qa
